// <auto-generated />
using System;
using HearHere.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HearHere.Shared.Data.Migrations
{
    [DbContext(typeof(HearHereDbContext))]
    partial class HearHereDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("UserId", "RecordingId")
                        .IsUnique()
                        .HasDatabaseName("uq_likes_user_recording");

                    b.ToTable("likes", (string)null);
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.ModerationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("from_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_id");

                    b.Property<string>("Scores")
                        .HasColumnType("jsonb")
                        .HasColumnName("scores");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId", "CreatedAt")
                        .HasDatabaseName("idx_moderation_records_recording_id");

                    b.ToTable("moderation_records", null, t =>
                        {
                            t.HasCheckConstraint("chk_moderation_action", "action IN ('auto_approve', 'auto_reject', 'escalate_to_review', 'manual_approve', 'manual_reject')");

                            t.HasCheckConstraint("chk_moderation_actor_type", "actor_type IN ('system', 'moderator', 'admin')");
                        });
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Play", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationSec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_sec");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId")
                        .HasDatabaseName("idx_plays_recording_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_plays_user_id");

                    b.ToTable("plays", (string)null);
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AudioBlobKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audio_blob_key");

                    b.Property<string>("AudioFormat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("aac")
                        .HasColumnName("audio_format");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<int?>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("like_count");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("LocationName")
                        .HasColumnType("varchar(300)")
                        .HasColumnName("location_name");

                    b.Property<string>("ModerationScores")
                        .HasColumnType("jsonb")
                        .HasColumnName("moderation_scores");

                    b.Property<int>("PlayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("play_count");

                    b.Property<string>("Region")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("pending_moderation")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("subject");

                    b.Property<string>("Transcript")
                        .HasColumnType("text")
                        .HasColumnName("transcript");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_recordings_pending_review")
                        .HasFilter("status = 'pending_review' AND deleted_at IS NULL");

                    b.HasIndex("Location")
                        .HasDatabaseName("idx_recordings_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_recordings_status_approved")
                        .HasFilter("status = 'approved' AND deleted_at IS NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_recordings_user_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("recordings", null, t =>
                        {
                            t.HasCheckConstraint("chk_recordings_audio_format", "audio_format IN ('aac', 'm4a', 'mp3')");

                            t.HasCheckConstraint("chk_recordings_category", "category IS NULL OR category IN ('history', 'nature', 'architecture', 'culture', 'personal', 'food', 'music', 'art', 'politics', 'science', 'other')");

                            t.HasCheckConstraint("chk_recordings_duration", "duration_sec > 0 AND duration_sec <= 300");

                            t.HasCheckConstraint("chk_recordings_status", "status IN ('pending_upload', 'pending_moderation', 'pending_review', 'approved', 'rejected')");
                        });
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.RecordingTag", b =>
                {
                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("RecordingId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("idx_recording_tags_tag_id");

                    b.ToTable("recording_tags", (string)null);
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("submitted")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_reports_status_open")
                        .HasFilter("status IN ('open', 'reviewing')");

                    b.HasIndex("RecordingId");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("UserId");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("chk_reports_reason_code", "reason_code IN ('hate_speech', 'harassment', 'violence', 'sexual_content', 'spam', 'misinformation', 'other')");

                            t.HasCheckConstraint("chk_reports_status", "status IN ('submitted', 'reviewing', 'resolved_removed', 'resolved_dismissed')");
                        });
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_tags_name");

                    b.ToTable("tags", null, t =>
                        {
                            t.HasCheckConstraint("chk_tags_name_lowercase", "name = lower(name)");
                        });
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarBlobKey")
                        .HasColumnType("text")
                        .HasColumnName("avatar_blob_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("uq_users_external_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_role", "role IN ('user', 'moderator', 'admin')");
                        });
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Like", b =>
                {
                    b.HasOne("HearHere.Shared.Data.Entities.Recording", "Recording")
                        .WithMany("Likes")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HearHere.Shared.Data.Entities.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.ModerationRecord", b =>
                {
                    b.HasOne("HearHere.Shared.Data.Entities.Recording", "Recording")
                        .WithMany("ModerationRecords")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Play", b =>
                {
                    b.HasOne("HearHere.Shared.Data.Entities.Recording", "Recording")
                        .WithMany("Plays")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HearHere.Shared.Data.Entities.User", "User")
                        .WithMany("Plays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Recording", b =>
                {
                    b.HasOne("HearHere.Shared.Data.Entities.User", "User")
                        .WithMany("Recordings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.RecordingTag", b =>
                {
                    b.HasOne("HearHere.Shared.Data.Entities.Recording", "Recording")
                        .WithMany("RecordingTags")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HearHere.Shared.Data.Entities.Tag", "Tag")
                        .WithMany("RecordingTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Report", b =>
                {
                    b.HasOne("HearHere.Shared.Data.Entities.Recording", "Recording")
                        .WithMany("Reports")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HearHere.Shared.Data.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HearHere.Shared.Data.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Recording", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("ModerationRecords");

                    b.Navigation("Plays");

                    b.Navigation("RecordingTags");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.Tag", b =>
                {
                    b.Navigation("RecordingTags");
                });

            modelBuilder.Entity("HearHere.Shared.Data.Entities.User", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Plays");

                    b.Navigation("Recordings");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
